### ISSUE TITLE
java.lang.NoClassDefFoundError: com.bumptech.glide.load.resource.drawable.GlideDrawable

### ISSUE THREAD

**Issue by liliangzdh** [DylanVann/react-native-fast-image#196]
<img width="790" alt="67dc7f0a58b142973aeaf9618b7576b8" src="https://user-images.githubusercontent.com/16744633/39390909-3653f136-4ace-11e8-8a55-fcfc7c5d3521.png">
<img width="764" alt="b002e19eebade75d446ab5ff78cf6619" src="https://user-images.githubusercontent.com/16744633/39390910-36aa89d8-4ace-11e8-9fa7-55ccd4731bd9.png">

 java.lang.NoClassDefFoundError: com.bumptech.glide.load.resource.drawable.GlideDrawable
                                                       at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
                                                       at java.lang.Class.getDexCacheType(Class.java:2551)
                                                       at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
                                                       at java.lang.reflect.Method.getParameterTypes(Method.java:193)
                                                       at java.lang.Class.getDeclaredMethods(Class.java:1812)
                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:426)
                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:320)
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:122)
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:116)
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:79)
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:66)
                                                       at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:205)
                                                       at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:147)
                                                       at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:94)
                                                       at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:224)
                                                       at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:148)
                                                       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:175)
                                                       at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:55)
                                                       at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:132)
                                                       at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:129)
                                                       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81)
                                                       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171)
                                                       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141)
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083)
                                                       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
                                                       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920)
                                                       at java.lang.Thread.run(Thread.java:776)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.load.resource.drawable.GlideDrawable" on path: DexPathList[[zip file "/data/app/aolei.ydniu-1/base.apk"],nativeLibraryDirectories=[/data/app/aolei.ydniu-1/lib/arm, /data/app/aolei.ydniu-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
                                                       at java.lang.Class.getDexCacheType(Class.java:2551) 
                                                       at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169) 
                                                       at java.lang.reflect.Method.getParameterTypes(Method.java:193) 
                                                       at java.lang.Class.getDeclaredMethods(Class.java:1812) 
                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:426) 
                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:320) 
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:122) 
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:116) 
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:79) 
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:66) 
                                                       at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:205) 
                                                       at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:147) 
                                                       at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:94) 
                                                       at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:224) 
                                                       at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:148) 
                                                       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:175) 
                                                       at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:55) 
                                                       at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:132) 
                                                       at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:129) 
                                                       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
                                                       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171) 
                                                       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141) 
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083) 
                                                       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113) 
                                                       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920) 
                                                       at java.lang.Thread.run(Thread.java:776)

**Comment by liliangzdh** [comment]
the glide Version is 3.8.0。 but another component need glide Version is 4.5.0。can you update the glide Version ？

**Comment by liliangzdh** [comment]
the Image Gidle Verion

**Comment by wudashuaige** [comment]
Is there a solution?

**Comment by DylanVann** [comment]
There isn't a solution yet. I don't know how to resolve that issue and haven't had time to take another look yet.

**Comment by jnrepo** [comment]
would down grading work?

**Comment by DylanVann** [comment]
@jnrepo If you're using Glide elsewhere in your app I'm not sure what will happen with this since `Glide` says to only use a single `AppGlideModule`, but you could try using the branch `feat/glide-4`, which is for this PR: https://github.com/DylanVann/react-native-fast-image/pull/201

```bash
yarn add github:DylanVann/react-native-fast-image#feat/glide-4
```

Let me know what happens.

**Comment by jnrepo** [comment]
@DylanVann thanks for that quick response, will keep you updated

**Comment by DylanVann** [comment]
On that branch I've just pushed a commit that will allow you to make this library depend on a specific glide version by using extra properties. Just add this to `android/build.gradle`:

```bash
project.ext {
    glideVersion = "4.6.1"
}
```

In this case theoretically any `4.x.x` version should work.

**Comment by jnrepo** [comment]
@DylanVann thanks! I was actually able to fix my issue. I found the other module that was using `glide` and excluded that version

```
    implementation(project(':react-native-smooch')) {
      exclude group: 'com.github.bumptech.glide', module: 'glide'
    }
```

and that seemed to fix my issue.

As with the `feat/glide-4` branch I tested it, but ran into this error:

```
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
/Users/user/project/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageOkHttpProgressGlideModule.java:39: error: cannot find symbol
    public void applyOptions(Context context, GlideBuilder builder) {builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888); }
                                              ^
  symbol:   class GlideBuilder
  location: class FastImageOkHttpProgressGlideModule
1 error
```

**Comment by DylanVann** [comment]
I tried it out myself and noticed that error. I pushed a commit that fixes it.

I'd be concerned that using that solution might break in some cases if `react-native-smooch` is expecting Glide 4 to be available.

**Comment by jnrepo** [comment]
@DylanVann cool, thank you so much! Tested the new version and works great

**Comment by DylanVann** [comment]
Well hopefully I can resolve that issue and get around to publishing it soon. For now you should be able to just point to the branch. Glad you've found a way to resolve this.

**Comment by DylanVann** [comment]
Update on this: https://github.com/DylanVann/react-native-fast-image/pull/201

Sort of an unfortunate situation with `Glide@4` and I'm not sure what the best solution is yet. Still thinking...

**Comment by wuyunqiang** [comment]
"react-native-fast-image": "^4.0.14"
yarn add react-native-fast-image
react native link 
and bug still here.

open react-native-fast-image android/build.gradle 
glide 3.8 still 

git clone https://github.com/DylanVann/react-native-fast-image.git
copy react-native-fast-image/android  to myproject/node_module/react-native-fast-image/android will be ok.

**Comment by jiasongs** [comment]
+1

**Comment by wsh794972562** [comment]
why you delete#201,then how can I resolve problem

**Comment by wsh794972562** [comment]
you latest version on master still have this problem

**Comment by DylanVann** [comment]
it's merged into master. the latest version on master uses Glide 4

**Comment by wsh794972562** [comment]
With your approach, iOS doesn't work, and you're missing the sdwebimag-related header files

**Comment by wsh794972562** [comment]
Even though I introduced sdwebimage myself, I still couldn't find the FLAnimatedImageView

**Comment by clytras** [comment]
When trying to use `yarn add github:DylanVann/react-native-fast-image` I get a yarn error:

`error Error parsing JSON at "https://raw.githubusercontent.com/DylanVann/react-native-fast-image/05830ad8a70f243dc4a6e089714866070f48f58a/package.json", "Unexpected token : in JSON at position 3".`

I guess I have to add glide dependencies manually for now.

**Comment by gpawlik** [comment]
I had the same problem after upgrading to `7.0.2` which I solved after updating dependency lock file: `cd android && ./gradlew generateLock saveLock`. Apparently `com.github.bumptech.glide` version was locked there and needed to be updated.
