### ISSUE TITLE
iOS - Caching Image failures

### ISSUE THREAD

**Issue by KevinColemanInc** [DylanVann/react-native-fast-image#394]
I am loading 20 images hosted in the USA on a very slow wifi connection from Asia. In the browser, the images fetch, but its slow.

From what I can tell FastImage if the image loading fails (`onError` is triggered), it seems to cache the error instead of trying again later. Only deleting the app and re-launching it again will FastImage be able to fetch the images again.

I don't know iOS / Swift well enough to confirm my hypothesis, but is anyone else seeing this?

**Comment by StevenMasini** [comment]
@KevinColemanInc I think I am experiencing the same issue as you. 

You are indeed right, I investigated the issue and right now on iOS when the "ImageCanvas" (I will call it like this) fail to download an image. Well first it fail silently, the error isn't being broadcast to the RN side, and second it won't try to download the image again.

So my issue is a bit different than yours. I notice this because in my app I have the same picture being display on several screen, and sometime it loads in some screen "ImageCanvas" but not in others.

e.g I have "ImageCanvas1" on page 1 who failed to download the image, then I push page 2 with "ImageCanvas2" who load successfully the picture. When I pop back to page 1 "ImageCanvas1" still haven't load the picture.

So I have fixed my issue on my own branch but haven't submit a PR for it yet. Also it's an iOS related issue, this doesn't reproduce on Android as Glide will automatically re-trigger the download if it fails.

But as I said your issue is different, and I should made a fix that handle all the scenario.

I will open a new PR for this, and will keep you updated about it.

**Comment by StevenMasini** [comment]
@KevinColemanInc I made a Pull Request that should fix your issue https://github.com/DylanVann/react-native-fast-image/pull/433

**Comment by StevenMasini** [comment]
@KevinColemanInc I think you can try my PR https://github.com/DylanVann/react-native-fast-image/pull/433 to see if it fix your problem. Let me know if you have feedback about it.

**Comment by KevinColemanInc** [comment]
@StevenMasini I pushed your fix out to production and I haven't seen it crash yet, but I also have not explicitly tested for this case.

**Comment by StevenMasini** [comment]
@KevinColemanInc Thank you for helping me out.

The PR include an auto-retry logic, so this should solve your problem. Let me know if you figured out anything else or if you have further feedbacks. 👍

**Comment by StevenMasini** [comment]
@KevinColemanInc Any updates ? Do you still have the crash ?

**Comment by evanjmg** [comment]
I'm still getting cache misses with your fork. Images don't or take a long time to load with excellent internet. There is definitely a lot less memory being used! Thank you so much for the work so far!

**Comment by StevenMasini** [comment]
@evanjmg What kind of caches misses ? Could you describe the problem ?

**Comment by fang0rnz** [comment]
hey @StevenMasini I'm having this weird cache behavior on android, does your PR fix this on android as well?

**Comment by KevinColemanInc** [comment]
@StevenMasini I had one user report caching failures on iOS. They claimed they couldn't see any images on their profile when they were successfully uploaded to the server. Not sure if this helps :-/ but this might still be a problem.

**Comment by evanjmg** [comment]
I'm getting this issue now. Had it today with the latest. Our users report this often.  If I go through 100+ images with some failing, they will never load again. I don't know the cause, but I'm still trying to create a reproducible app

**Comment by StevenMasini** [comment]
@fang0rnz sorry my fix only concern iOS, I don't know anything about native Android 🙃 

Let me recap what happened with my fix.

The version [v5.3.0](https://github.com/DylanVann/react-native-fast-image/releases/tag/v5.3.0) only integrated the fixes related to memory leaks on iOS.

I suggested other fixes back then, related to image cache, but @DylanVann decided to not integrate them because they break the parity between iOS and Android (which I understand and agree).

Nevertheless for my app on production at my company, I am still using my own fork for `react-native-fast-image`, which integrate two fixes for image cache.

1. Auto-retry when an image fail to download (will retry 3 times, before giving up). This should solve your issue @evanjmg 
2. Notify all the instance sharing the same `url`, when one of them succeed to download the resource. This is useful if you have similar images appearing on different screens.

@KevinColemanInc @evanjmg feel free to try my module. You can find the instruction [here](https://github.com/DylanVann/react-native-fast-image/pull/433#issuecomment-475118179). Let me know if it helped or not.

**Comment by KevinColemanInc** [comment]
@StevenMasini I am using: [#27e9e](/StevenMasini/react-native-fast-image/commit/27e9eacc0c9cca6fa16ec8d342a8d804b926c6df) in production and I am still experiencing this issue.

IMHO, if the image fetch gets a 5xx response, we should try again in a few days, if its a 4xx response, we should stop. If its a timeout, we should just keep trying until we get one of the above http codes with exponential back off.

Btw, thanks for working on fixing this!

**Comment by antitoine** [comment]
For people who still have a problem with image loading on iOS, here a workarround I used directly in React Native :
```js
const MAX_RELOAD_FAST_IMAGE = 10;

const Image = (props) => {
  const [fastImageKey, setFastImageKey] = useState(1);
  return <FastImage key={fastImageKey} onError={() => {
    if (fastImageKey < MAX_RELOAD_FAST_IMAGE) {
      setFastImageKey(fastImageKey+1);
    } else {
      console.warn('Fast Image error occur, max increment reach, the image won\'t be displayed');
    }
  }} {...props}/>;
};
```
This work great, but keep in mind that is a very bad approch...
I'm using react-native-fast-image 6.1.1 and RN 0.59.9.

**Comment by babyrusa** [comment]
@StevenMasini For the #2 `Notify all the instance sharing the same url, when one of them succeed to download the resource. This is useful if you have similar images appearing on different screens.`
is this library not supporting caching the same image URL on different screens/components? I've been noticing that since I'm testing my app and notices same images on different components/screens are not cached, the app calls the server every time. I'm not sure if I'm right so I've been searching for the answer.
Thank you

**Comment by StevenMasini** [comment]
@babyrusa it has been so long since I worked on this issue. I am not working on the project where I used this framework anymore, so it's very hard for me to answer your question.

From what I remember the issue is that you need to find a way for components in other parts of your application to reload when the image is fetched.

**Comment by babyrusa** [comment]
@StevenMasini  Thank you for getting back to me. Could you clarify what you meant by "component to **reload** ", like reload as in rerender/reload the image?

**Comment by StevenMasini** [comment]
Yes they need to refresh, like a `props` or `stats` needs its value to change for the component to reload. Since other components in other views don't won't have any property that will change when the image request will complete download, these components won't reload.
