### ISSUE TITLE
ANDROID Invariant Violation: requireNativeComponent: "FastImageView" was not found in the UIManager.

### ISSUE THREAD

**Issue by sobhan-shahamatnia** [DylanVann/react-native-fast-image#517]
Invariant Violation: requireNativeComponent: "FastImageView" was not found in the UIManager.

This error is located at:
    in FastImageView (at src/index.js:49)
    in RCTView (at View.js:45)
    in View (at src/index.js:48)
    in FastImageBase (at src/index.js:68)
    in FastImage (at categoryPage.js:278)
    in RCTView (at View.js:45)
    in View (at categoryPage.js:277)
    in RCTView (at View.js:45)
    in View (at categoryPage.js:275)
    in RCTView (at View.js:45)
    in View (at VirtualizedList.js:1762)
    in CellRenderer (at VirtualizedList.js:688)
    in RCTView (at View.js:45)
    in View (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at VirtualizedList.js:1081)
    in VirtualizedList (at FlatList.js:632)
    in FlatList (at categoryPage.js:357)
    in RCTView (at View.js:45)
    in View (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at KeyboardAwareHOC.js:508)
    in KeyboardAwareScrollView (at Content.js:125)
    in Content (at connectStyle.js:384)
    in Styled(Content) (at categoryPage.js:356)
    in RCTView (at View.js:45)
    in View (at Container.js:15)
    in Container (at connectStyle.js:384)
    in Styled(Container) (at categoryPage.js:340)
    in CategoryPage (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:37)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:26)
    in ResourceSavingScene (at createBottomTabNavigator.js:121)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at createBottomTabNavigator.js:111)
    in RCTView (at View.js:45)
    in View (at createBottomTabNavigator.js:110)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:429)
    in NavigationContainer (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

Dependency versions :

- React Native version:0.59.9
- React version:16.8.3
- React Native Fast Image version:^7.0.2

**Comment by fardeenpanjwaniucmouli** [comment]
what was causing the issue?

**Comment by Villar74** [comment]
Having the same issue, just imported it in project and used

```
import Image from 'react-native-fast-image'

<Image
            resizeMode={Image.resizeMode.contain}
            source={require('js/resources/img/logo.png')}
            style={styles.logo}
          />
```

**Comment by Villar74** [comment]
oh mb i try to load local img, thats the problem?

**Comment by brkrtp** [comment]
I have to same issue +1 @Villar74 your solutions not working for me

**Comment by Villar74** [comment]
@brkrtp that was not a solution) it was explaining how i get that error)

Fixed with init new project, carefully move there my files and added last version of react-native-fast-image

**Comment by jose920405** [comment]
+1

**Comment by kennetpostigo** [comment]
Upgraded today and still see this error happening

**Comment by Adnan-Hussain22** [comment]
Still having the same issue on android.
react-native:0.59.5
react-native-fast-image: ^7.0.2
react: 16.8.3

**Comment by Villar74** [comment]
Not having that issue with auto-linking on 0.60.4

**Comment by tianliuj** [comment]
I have upgrade the leaste version 7.0.2 
but I also have the problem, who can help me?

**Comment by wvalen** [comment]
I have the same issue when i use react-native 0.60.
Works after input those:
<<
react-native link react-native-fast-image
react-native run-android
>>

It looks like that  React Native CLI uses autolinking for native dependencies not works,
we have to link by ourself. Maybe i'm wrong, but can have a try.

**Comment by kishanbharda** [comment]
Have anyone found solution ?

**Comment by valeriik** [comment]
for iOS: In my case of CocoaPods in project it was fixed by:
```
cd ~/[your_project_folder]; 
sudo rm -rf node_modules; 
npm install; 
cd ios/; 
rm -rf Pods; 
rm Podfile.lock; 
pod install; 
cd ../ ; 
rm -rf ios/build ; 
sudo rm -rf ~/Library/Developer/Xcode/DerivedData
```

**Comment by latovicalmin** [comment]
I had same issue on iOS - `pod install` resolved it.

**Comment by FunkyLambda** [comment]
WTF was this closed!? It's clearly not f%$&^@$ resolved.

Also @valeriik , irrelevant. Question is about Android not iOS.

**Comment by kelvinkhai** [comment]
Android app build success, but crash straight away when the app start. 
iOS working fine after running "pod install" command in the ios folder.

Following @wvalen answer, android version worked after running "react-native link react-native-fast-image".

I thought react native document state that native modules are autolinked after > 0.60 version. But the autolinked doesn't work in this package. Maybe this solution should be included in the documentation

react-native: 0.60.4
react-native-fast-image: 7.0.2
react: 16.8.6



> I have the same issue when i use react-native 0.60.
> Works after input those:
> <<
> react-native link react-native-fast-image
> react-native run-android
> 
> > >
> 
> It looks like that React Native CLI uses autolinking for native dependencies not works,
> we have to link by ourself. Maybe i'm wrong, but can have a try.

**Comment by danielfein** [comment]
Any ideas? Also weird folks would talk about iOS, title's first word is Android.

**Comment by loq24** [comment]
Same issue for me. Any solution to this problem?

**Comment by FahRamatis** [comment]
I just re run react-native run-android and all works fine

**Comment by rdgomt** [comment]
I've just realized that I had not properly linked (aka manually) the library.

I'm at RN 0.59.10. and react-native-fast-image@6.1.1

**Comment by changweining** [comment]
I solve this problemI。I`m at react-native: 0.6.15.

follow it：

https://github.com/DylanVann/react-native-fast-image/blob/4fa62bb09f65d967977f25ef87eda5f8b7c18cd6/docs/installation-manual.md

**Comment by eramudeep** [comment]
> I had same issue on iOS - `pod install` resolved it.

yes. Pod installed solved the problem for ios.
but having trouble with android.

**Comment by rahamin1** [comment]
For me (using 0.59.9 on ios), adding the library manually, as described in https://github.com/DylanVann/react-native-fast-image/blob/4fa62bb09f65d967977f25ef87eda5f8b7c18cd6/docs/installation-manual.md#ios

**Comment by srmono** [comment]
After manual link also still showing the same issue

Invariant Violation: requireNativeComponent: "FastImageView" was not found in the UIManager.

Properly linked manually, cleaned gradlew , still same issue. not sure what is the reason

**Comment by getmanzooronline** [comment]
I'm also having the same issue.
"react-native-fast-image": "^8.3.1"

**Comment by srmono** [comment]
> I'm also having the same issue.
> "react-native-fast-image": "^8.3.1"

let me know if you find solution. as of now i removed this and working on other features without wasting time

**Comment by thanh90** [comment]
manual link on android did work for me

**Comment by srmono** [comment]
> on

I have done manual link only. I lest using auto linking since there were many issues with auto linking
