### ISSUE TITLE
iOS "Camera Roll" Images rendering as white views

### ISSUE THREAD

**Issue by aIacoella** [DylanVann/react-native-fast-image#543]
ONLY on iOS when rendering device cached images from camera roll the component renders white views. 

1. Get images paths from react native's camera roll
2. Render FastImage with that uri

Expected behavior
Normal image rendering.

**Dependency versions**

- React Native version: 0.60.4
- React version: 18.8.6
- React Native Fast Image version: 7.0.2

**Comment by Jarred-Sumner** [comment]
To add support for camera roll:
1. Install this library: https://github.com/SDWebImage/SDWebImagePhotosPlugin
2. Rewrite the source URI's you get from `react-native-camera-roll` to start with `photos://asset/` instead of `ph://`

Example code (for step 2):
```javascript
import FastImage from "react-native-fast-image";
import React from "react";
import hoistNonReactStatics from "hoist-non-react-statics";

const CustomFastImage = React.forwardRef(({ source, ...props }, ref) => {
  if (
    typeof source === "object" &&
    typeof source.uri === "string" &&
    source.uri.startsWith("ph://")
  ) {
    const { uri, ...otherSource } = source;
    return (
      <FastImage
        ref={ref}
        source={{
          uri: uri.replace("ph://", "photos://asset/"),
          ...otherSource
        }}
        {...props}
      />
    );
  } else {
    return <FastImage ref={ref} source={source} {...props} />;
  }
});

export const Image = hoistNonReactStatics(CustomFastImage, FastImage);
```

You'd also want to set it not to cache the images

**Comment by aIacoella** [comment]
Thank you, I will definitely try this in the next days and I'll let you know.

**Comment by eyu0415** [comment]
SDWebImagePhotosDefine.h in SDWebImagePhotosPlugin 

the @import SDWebImage has error 

"Module SDWebImage not found"

**Comment by bobber205** [comment]
@eyu0415 Seeing the same thing after following the installation instructions.

**Comment by bobber205** [comment]
@Jarred-Sumner Do you have an example project on with FastImage and RN and SDWebImage installed and working?

**Comment by bakerac4** [comment]
@dreampiggy Im also seeing the error above? Any ideas

**Comment by dreampiggy** [comment]
> SDWebImagePhotosDefine.h in SDWebImagePhotosPlugin
> 
> the @import SDWebImage has error
> 
> "Module SDWebImage not found"

What's the install method, why does not SDWebImage a clang module ? This import issue seems a little strange. Any demo here ?

**Comment by priteshbaviskar** [comment]
@dreampiggy 
I installed the plugin using CocoaPods as mentioned on https://github.com/SDWebImage/SDWebImagePhotosPlugin
`pod SDWebImagePhotosPlugin` followed by `pod install`
Running into the same issue.

**Comment by dreampiggy** [comment]
> @dreampiggy
> I installed the plugin using CocoaPods as mentioned on https://github.com/SDWebImage/SDWebImagePhotosPlugin
> `pod SDWebImagePhotosPlugin` followed by `pod install`
> Running into the same issue.

Can you provide a simple demo, contains:

1. React-Native App
2. Add react-native-fast-image
3. Add react-native-camera-roll
4. Add SDWebImagePhotosPlugin

So that I can find out the reason ?

From the description, I guess this maybe something related to `react-native-fast-image` (which bundle SDWebImage into the sub-project), does not supports clang module. Using standalone SDWebImage should support clang module and so works for that `@import SDWebImage`.

The `@import SDWebImage` is required to be used for Swift Pacage Manager support (Because it's a native library, React-Native users are one of our users), so we can not simply remove that. Need to find out a workaround.

**Comment by dreampiggy** [comment]
I guess I know the reason. CocoaPods's static library is not supported by PhotosPlugin. I'll push a new version to support both of them (Sounds tricky)

For now, you can add this into your Podfile:

```ruby
use_modular_headers! #important
pod 'SDWebImage', "~> 5.0"
pod 'SDWebImagePhotosPlugin', "~> 1.0"
```

**Comment by dreampiggy** [comment]
@priteshbaviskar @bakerac4 @bobber205 For the compile error of that module import, you can either upgrade to the [Photos Plugin V1.0.1](https://github.com/SDWebImage/SDWebImagePhotosPlugin/releases/tag/1.0.1) version, or using the `use_modular_headers!` in CocoaPods instead. Which should fix it.

**Comment by pxpeterxu** [comment]
Thanks @dreampiggy for the pointers!

For those running into the same issue, these are the steps I took as of April, 2020 to get the photos displaying:

1.  Install `SDWebImagePhotosPlugin` by adding the following to your `Podfile` and then running `pod install`
    ```rb
    pod 'SDWebImagePhotosPlugin'
    ```

2.  Edit my `AppDelegate.m`:
    ```objectivec
    // At the top
    #import <SDWebImage/SDWebImage.h>
    #import <SDWebImagePhotosPlugin/SDImagePhotosLoader.h>

    // Within `didFinishLaunchingWithOptions`
    - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
    {
      // ...
      [SDImageLoadersManager.sharedManager addLoader:SDImagePhotosLoader.sharedLoader];
      SDWebImageManager.defaultImageLoader = SDImageLoadersManager.sharedManager;

      // ...
      // If there's no return statement already, add the following:
      return YES;
    }
    ```

3. Build onto your device/simulator

Thanks @Jarred-Sumner for pointing me in the right direction! Note that that comment is a bit outdated now: `ph://...` URLs will already work out of the box, as @dreampiggy had added support in [`SDWebImagePhotosPlugin` v1.0.0](https://github.com/SDWebImage/SDWebImagePhotosPlugin/releases/tag/1.0.0)

**Comment by remigallego** [comment]
I followed your steps @pxpeterxu but it didn't solve the problem for me, I still have a white image in place of the actual image.

**Comment by pxpeterxu** [comment]
@remigallego I actually don't recommend using the `SDWebImagePhotosPlugin` in general anymore after testing this with our app: SDWebImage doesn't have an idea of how large the photo to render should be, so it ends up loading the full-size, ~4000x3000 photo into memory. Instead, I recommend for now that you just use the regular `react-native` `<Image />` to load these photos for now.

**Comment by dreampiggy** [comment]
> @remigallego I actually don't recommend using the `SDWebImagePhotosPlugin` in general anymore after testing this with our app: SDWebImage doesn't have an idea of how large the photo to render should be, so it ends up loading the full-size, ~4000x3000 photo into memory. Instead, I recommend for now that you just use the regular `react-native` `<Image />` to load these photos for now.

See Readme. We already provide the **Native API** to control the Photo loading size, rendering mode, image type (Normal Image/LivePhoto/GIF/Video Poster).

The only thing you do, it's to write JavaScript wrapper. This is not the part of SDWebImage organization's duty to do. That it's react-native-fast-image or react-native-fast-image-photos's duty.

**Comment by dreampiggy** [comment]
If you want to control a hard limit of size in global, you can do the same thing in Native API via []()

```swift
SDWebImageManager.shared.optionsProcessor = SDWebImageOptionsProcessor { options, context in
    var options = options ?: []
    var context = context ?: [:]
    if let requestOptions = requestOptions {
        // limit 1000x1000
        requestOptions.sd_targetSize = CGSize(width: 1000, 1000)
    } else {
        let requestOptions = PHImageRequestOptions()
        requestOptions.networkAccessAllowed = true
        requestOptions.sd_targetSize = CGSize(width: 1000, 1000)
        context[.photosImageRequestOptions] = requestOptions
    }
    return SDWebImageOptionsResult(options: options, context: context)
}
```

**Comment by dreampiggy** [comment]
SDWebImagePhotosPlugin released [v1.1.0](https://github.com/SDWebImage/SDWebImagePhotosPlugin/releases/tag/1.1.0).

This version change the **Default Query Image Size** from full pixel size, into the largest size system provide (which is smaller than full size, based on iOS System optimization).

It's still recommaned to use native API to specify the global fetch size limit. Until react-native-fast-image itself provide the JavaScript bridge API (for example, pass the <Image> component size for querying image size).

**Comment by exception** [comment]
Almost a year later, this issue is still happening. Anyone got any idea on how to fix it properly?

**Comment by hantrungkien** [comment]
@dreampiggy PH Asset photo is loaded with SDWebImage Photos Plugin but PH asset video is white, do you have any solution?

**Comment by dreampiggy** [comment]
@hantrungkien 
I didn't test that `PH asset video is white`. Maybe a sample and re-producable demo is better for me to investigate.

And, you can fire a issue here https://github.com/SDWebImage/SDWebImagePhotosPlugin/issues/new/choose

**Comment by sen46Sko** [comment]
2025
Issue still exist 😢
